### ISSUE TITLE
Add Java Wrapper

### ISSUE THREAD

**Issue by Mizux** [Mizux/cmake-swig#1]
Need to build Java wrapper

**Comment by msteinbeck** [comment]
Hi @Mizux,

I stumbled across your repository while searching a solution for RPATHs on OSX for shared libraries generated with Swig/CMake. I noticed that you are trying to add wrappers for Java and C#. I'm using Swig/CMake to generate several bindings for a C/C++ library: https://github.com/msteinbeck/tinyspline. Maybe you'll find some useful snippets.

**Comment by Mizux** [comment]
Forgot to reply,

0. Many thanks for the sample !

1. I've read your https://github.com/msteinbeck/tinyspline/blob/86a4e09329e2914f0b8830aed2e1b347d927b2d0/src/CMakeLists.txt#L1238-L1306
BUT I wanted to generate a **maven package** (with GPG sign enable) so I could upload it to Maven Central using OSS Sonatype repo/workflow.

2. We already had the "javac" direct compilation for years in our google/or-tools Makefile based build but again here I wanted to experiment and create a Maven package than simply port our Makefile stuff to CMake.
