### ISSUE TITLE
Unknown CMake command "swig_add_library"

### ISSUE THREAD

**Issue by allebacco** [Mizux/cmake-swig#3]
The `swig_add_library` has been added in CMake 3.8, but the project is requiring CMake 3.5.2.

The minimum requirement should be bumped at least to CMake 3.8.

**Comment by Mizux** [comment]
Thanks for this input !

 BTW CMake [UseSWIG](https://cmake.org/cmake/help/latest/module/UseSWIG.html) builtin package has evolved a lot in 3.11 (with minor changes up to 3.14)

So I'm thinking on adding a minimum cmake version to 3.14 than trying to support the old behaviour...
