### ISSUE TITLE
How to test in python?

### ISSUE THREAD

**Issue by Athius** [Mizux/cmake-swig#6]
Hi!

Once the build is done, I install the python module using setup.py. Inside my python interpreter I do a import CMakeSwig but after that, I don't find the method and class Foo, FooBar...
What did I do wrong?

For information, I'm on windows 10 1909, with python 3.8.1, CMake 3.14.5 and Visual Studio 2017

Thank you

**Comment by Mizux** [comment]
take a look at the "unit test" -> https://github.com/Mizux/cmake-swig/blob/master/cmake/test.py

Example libFoo binding will be in:
https://github.com/Mizux/cmake-swig/blob/0cb5b1fb3f7290be3780be3c0f7a7620ae4029a2/Foo/python/CMakeLists.txt#L6
i.e. `CMakeSwig.Foo` and the file is:
https://github.com/Mizux/cmake-swig/blob/0cb5b1fb3f7290be3780be3c0f7a7620ae4029a2/Foo/python/CMakeLists.txt#L2
i.e. `pyFoo.py`

So the full arborescence is: `CMakeSwig.Foo.pyFoo.py`

doc: https://github.com/Mizux/cmake-swig/blob/master/doc/python.md#build-directory-layout
