### ISSUE TITLE
.Net support with XCode generator is broken

### ISSUE THREAD

**Issue by Mizux** [Mizux/cmake-swig#9]
Need to reuse mizux/dotnet-native last development...

**Comment by kurtsansom** [comment]
can you provide a little more detail on this issue. I just found this and specifically want to test the .Net support.

**Comment by Mizux** [comment]
Code is a little bit outdated, last development can be found in https://github.com/Mizux/dotnet-native/blob/main/cmake/dotnet.cmake so just need to sync both code base ASAP...

BUT during the refactor I've broken the macOS Xcode CI
see: https://github.com/Mizux/dotnet-native/runs/3004157908?check_suite_focus=true
